# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mongo:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

# Job: run tests
test:
  stage: test
  script:
   - npm install
   - npm test

# Unused
# test_db:
#  script:
#   - npm install
#   - node ./specs/start.js ./specs/db-postgres.spec.js

# Job: deploy to production
deploy:
  stage: deploy
  script: /scripts/deploy.sh
  environment:
    name: production
  
